package jinvoicepro;

public class ResultsFilesView extends javax.swing.JPanel {


	public ResultsFilesView () {
		initComponents ();
		splitPanel.setDividerLocation(350);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        tablePanel1 = new importacion.TablePanel();
        tablePanel2 = new importacion.TablePanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPanel.setPreferredSize(new java.awt.Dimension(486, 400));

        tablePanel1.setMinimumSize(new java.awt.Dimension(53, 400));
        tablePanel1.setPreferredSize(new java.awt.Dimension(484, 200));
        splitPanel.setTopComponent(tablePanel1);

        tablePanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores detectados:"));
        tablePanel2.setMaximumSize(new java.awt.Dimension(600, 300));
        tablePanel2.setMinimumSize(new java.awt.Dimension(53, 200));
        tablePanel2.setPreferredSize(new java.awt.Dimension(200, 200));
        splitPanel.setRightComponent(tablePanel2);

        add(splitPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane splitPanel;
    private importacion.TablePanel tablePanel1;
    private importacion.TablePanel tablePanel2;
    // End of variables declaration//GEN-END:variables
}
