package widgets;

import main.Controller;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

public class BotInteractionPanel extends javax.swing.JPanel {

	Controller controller;

	public BotInteractionPanel () {
		initComponents ();
	}

	public void setController (Controller controller) {
		this.controller = controller;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    currentButton = new javax.swing.JButton();

    currentButton.setText("Digitar documento al ECUAPASS");
    currentButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        currentButtonActionPerformed(evt);
      }
    });
    add(currentButton);
  }// </editor-fold>//GEN-END:initComponents

    private void currentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentButtonActionPerformed

		controller.onBotSubmitCurrent ();
    }//GEN-LAST:event_currentButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton currentButton;
  // End of variables declaration//GEN-END:variables
}
