package widgets;

import main.Controller;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class InputsControlPanel extends javax.swing.JPanel {

	Controller controller;

	public InputsControlPanel () {
		initComponents ();
	}

	public void setController (Controller controller) {
		this.controller = controller;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    selectAllButton = new javax.swing.JButton();
    alistarButton = new javax.swing.JButton();
    processingButton = new javax.swing.JButton();
    reinitializeButton = new javax.swing.JButton();

    setMaximumSize(new java.awt.Dimension(32767, 40));
    setMinimumSize(new java.awt.Dimension(327, 40));
    setPreferredSize(new java.awt.Dimension(400, 40));

    selectAllButton.setText("Seleccionar todos");
    selectAllButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectAllButtonActionPerformed(evt);
      }
    });
    add(selectAllButton);

    alistarButton.setText("Alistar");
    alistarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        alistarButtonActionPerformed(evt);
      }
    });
    add(alistarButton);

    processingButton.setText("Procesar...");
    processingButton.setEnabled(false);
    processingButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        processingButtonActionPerformed(evt);
      }
    });
    add(processingButton);

    reinitializeButton.setText("Borrar");
    reinitializeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reinitializeButtonActionPerformed(evt);
      }
    });
    add(reinitializeButton);
  }// </editor-fold>//GEN-END:initComponents

    private void alistarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alistarButtonActionPerformed
		try {
			controller.onSendSelectedFiles ();
		} catch (FileNotFoundException ex) {
			Logger.getLogger (InputsControlPanel.class.getName()).log (Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_alistarButtonActionPerformed

    private void reinitializeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinitializeButtonActionPerformed
		controller.onReinitialize ();
    }//GEN-LAST:event_reinitializeButtonActionPerformed

    private void processingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processingButtonActionPerformed
        controller.onStartProcessing ();
    }//GEN-LAST:event_processingButtonActionPerformed

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
		controller.onSelectAllFiles ();
    }//GEN-LAST:event_selectAllButtonActionPerformed
public void enableProcessingButton (boolean value) {
	processingButton.setEnabled (value);
}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton alistarButton;
  private javax.swing.JButton processingButton;
  private javax.swing.JButton reinitializeButton;
  private javax.swing.JButton selectAllButton;
  // End of variables declaration//GEN-END:variables
}
