/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package widgets;

import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.Controller;

/**
 *
 * @author lg
 */
public class WorkingCountryPanel extends javax.swing.JPanel {

	Controller controller;

	/**
	 * Creates new form WorkingCountryPanel
	 */
	public WorkingCountryPanel (Component parent) {
		initComponents ();
	}

	void setController (Controller controller) {
		this.controller = controller;
	}

	public static void main (String[] args) {
		JFrame fr = new JFrame ("Test Frame");
		fr.setVisible (true);
		fr.setSize (500,500);
		WorkingCountryPanel wcp = new WorkingCountryPanel (fr);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    colombiaButton = new javax.swing.JButton();
    ecudorButton = new javax.swing.JButton();
    titleLabel = new javax.swing.JLabel();

    colombiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon-colombia.png"))); // NOI18N
    colombiaButton.setText("Colombia");
    colombiaButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        colombiaButtonActionPerformed(evt);
      }
    });

    ecudorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon-ecuador.png"))); // NOI18N
    ecudorButton.setText("Ecuador");
    ecudorButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ecudorButtonActionPerformed(evt);
      }
    });

    titleLabel.setBackground(new java.awt.Color(204, 204, 255));
    titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleLabel.setText("Seleccione su ubicación actual:");
    titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
              .addComponent(colombiaButton)
              .addGap(5, 5, 5)
              .addComponent(ecudorButton)))
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 224, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 62, Short.MAX_VALUE)
          .addComponent(titleLabel)
          .addGap(12, 12, 12)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colombiaButton)
            .addComponent(ecudorButton))
          .addGap(0, 62, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void colombiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colombiaButtonActionPerformed
		controller.onWorkingCountrySelected ("colombia");
  }//GEN-LAST:event_colombiaButtonActionPerformed

  private void ecudorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecudorButtonActionPerformed
		controller.onWorkingCountrySelected ("ecuador");
  }//GEN-LAST:event_ecudorButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton colombiaButton;
  private javax.swing.JButton ecudorButton;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables
}
