/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package documento;

import javax.swing.JTextField;

/**
 *
 * @author lg
 */
public class SettingsPanel extends javax.swing.JPanel {

	SettingsController controller;

	public SettingsPanel () {
		initComponents ();
	}

	public void setController (SettingsController controller) {
		this.controller = controller;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ConfigurationPanel = new javax.swing.JPanel();
    companyLabel = new javax.swing.JLabel();
    companyField = new javax.swing.JTextField();
    ecuapassdocsLabel = new javax.swing.JLabel();
    ecuapassdocsField = new javax.swing.JTextField();
    codebiniLabel = new javax.swing.JLabel();
    codebiniField = new javax.swing.JTextField();
    ecuapassLabel = new javax.swing.JLabel();
    ecuapassField = new javax.swing.JTextField();
    panelOptions = new javax.swing.JPanel();
    saveButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    ConfigurationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración"));
    ConfigurationPanel.setPreferredSize(new java.awt.Dimension(700, 116));
    ConfigurationPanel.setLayout(new java.awt.GridLayout(4, 2));

    companyLabel.setText("Empresa:");
    ConfigurationPanel.add(companyLabel);

    companyField.setText("Empresa");
    ConfigurationPanel.add(companyField);

    ecuapassdocsLabel.setText("URL EcuapassDocs");
    ConfigurationPanel.add(ecuapassdocsLabel);

    ecuapassdocsField.setText("URL EcuapassDocs");
    ConfigurationPanel.add(ecuapassdocsField);

    codebiniLabel.setText("URL Codebini");
    ConfigurationPanel.add(codebiniLabel);

    codebiniField.setText("URL Codebini");
    ConfigurationPanel.add(codebiniField);

    ecuapassLabel.setText("URL ECUAPASS:");
    ConfigurationPanel.add(ecuapassLabel);

    ecuapassField.setText("URL ECUAPASS");
    ConfigurationPanel.add(ecuapassField);

    add(ConfigurationPanel, java.awt.BorderLayout.CENTER);

    saveButton.setText("Guardar");
    saveButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveButtonActionPerformed(evt);
      }
    });
    panelOptions.add(saveButton);

    cancelButton.setText("Cancelar");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    panelOptions.add(cancelButton);

    add(panelOptions, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

  private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		controller.onSaveButton ();
  }//GEN-LAST:event_saveButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		// TODO add your handling code here:
		System.exit (0);
  }//GEN-LAST:event_cancelButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ConfigurationPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField codebiniField;
  private javax.swing.JLabel codebiniLabel;
  private javax.swing.JTextField companyField;
  private javax.swing.JLabel companyLabel;
  private javax.swing.JTextField ecuapassField;
  private javax.swing.JLabel ecuapassLabel;
  private javax.swing.JTextField ecuapassdocsField;
  private javax.swing.JLabel ecuapassdocsLabel;
  private javax.swing.JPanel panelOptions;
  private javax.swing.JButton saveButton;
  // End of variables declaration//GEN-END:variables
		

	public JTextField getCompanyField () {
		return companyField;
	}	
	public JTextField getEcuapassdocsField () {
		return ecuapassdocsField;
	}
	public javax.swing.JTextField getCodebiniField () {
		return codebiniField;
	}
	public JTextField getEcuapassField () {
		return ecuapassField;
	}

}
