/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package documento;

import javax.swing.JTextField;

/**
 *
 * @author lg
 */
public class SettingsPanel extends javax.swing.JPanel {

	SettingsController controller;

	public SettingsPanel () {
		initComponents ();
	}

	public void setController (SettingsController controller) {
		this.controller = controller;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    empresaLabel = new javax.swing.JLabel();
    empresaField = new javax.swing.JTextField();
    creadorLable = new javax.swing.JLabel();
    creadorField = new javax.swing.JTextField();
    ecuapassLabel = new javax.swing.JLabel();
    ecuapassField = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    saveButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración"));
    jPanel1.setPreferredSize(new java.awt.Dimension(700, 116));
    jPanel1.setLayout(new java.awt.GridLayout(3, 2));

    empresaLabel.setText("Empresa:");
    jPanel1.add(empresaLabel);

    empresaField.setText("Empresa");
    jPanel1.add(empresaField);

    creadorLable.setText("URL Creador Documentos:");
    jPanel1.add(creadorLable);

    creadorField.setText("URL Creador");
    jPanel1.add(creadorField);

    ecuapassLabel.setText("URL ECUAPASS:");
    jPanel1.add(ecuapassLabel);

    ecuapassField.setText("URL ECUAPASS");
    jPanel1.add(ecuapassField);

    add(jPanel1, java.awt.BorderLayout.CENTER);

    saveButton.setText("Guardar");
    saveButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveButtonActionPerformed(evt);
      }
    });
    jPanel2.add(saveButton);

    cancelButton.setText("Cancelar");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    jPanel2.add(cancelButton);

    add(jPanel2, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

  private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		controller.onSaveButton ();
  }//GEN-LAST:event_saveButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		// TODO add your handling code here:
		System.exit (0);
  }//GEN-LAST:event_cancelButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField creadorField;
  private javax.swing.JLabel creadorLable;
  private javax.swing.JTextField ecuapassField;
  private javax.swing.JLabel ecuapassLabel;
  private javax.swing.JTextField empresaField;
  private javax.swing.JLabel empresaLabel;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JButton saveButton;
  // End of variables declaration//GEN-END:variables

	public JTextField getCreadorField () {
		return creadorField;
	}

	public JTextField getEcuapassField () {
		return ecuapassField;
	}

	public JTextField getEmpresaField () {
		return empresaField;
	}


	public void setCreadorField (String creadorField) {
		this.creadorField.setText (creadorField);
	}

	public void setEcuapassField (String ecuapassField) {
		this.ecuapassField.setText (ecuapassField);
	}

	public void setEmpresaField (String empresaField) {
		this.empresaField.setText (empresaField);
	}

}
